### PR TITLE
Add Code Analysis to build process

### PR DESCRIPTION
**Pull request by shiftkey**
TODO:
- [x] enable FxCop for Shimmer.Core
- [ ] enable FxCop for Shimmer.Client
- [ ] review and clean up critical defects
- [ ] review and clean up warnings

### CODE REVIEW

**Comment by anaisbetts** [comment]
Whyyyyyyyy would you do this. FxCop is awful, it makes the build 2x slower, it's inconsistent between VS versions, and I can think of exactly _one_ actually meaningful error that I make that it catches ("Specify CultureInfo on string formatters")

**Comment by shiftkey** [comment]
@paulcbetts I knew I'd get your attention with this. Take a deep breath, this isn't something I'm rushing into.

The reason why I've put it off until now (at least) is three-fold:

1) priorities - there's other things I can ship right now which are of higher-value
2) the things it finds on first use are mostly noise (as you mentioned)
3) it's rather dogmatic (thou shalt implement all the expected ctors for your custom exceptions)

I've also been hacking on getting proper Code Contracts specs into the codebase, which I think is more valuable to the overall scheme of things.

> it makes the build 2x slower

True

> it's inconsistent between VS versions

Personally, I'd rather run the command line tool rather than use the VS integration - use it as part of the CI scripts rather than have it in the face of developers all the time.

Fun anecdote: in a past life I wrote some custom FxCop warnings to ensure a customer was using an ORM correctly and not causing LINQ queries to execute on the client (and download b-b-b-billions of records too)

**Comment by anaisbetts** [comment]
Sure, but the command line versions are no better, unless you're actually checking the FxCop binaries into the repo, you'll get the same "Works here but not there" silliness. I'm :+1: on Code Contracts though

**Comment by shiftkey** [comment]
Ok, I'll get Code Contracts updated and enhanced in the codebase first. That's been far more valuable for finding bugs anyway (in my recent experiences).

**Pull request closed without merging**
