### PR TITLE
Fixed exception if a package has no dependencies

### PR DESCRIPTION
**Pull request by thoemmi**
The code failed when the package has no dependencies

### CODE REVIEW

**Comment by anaisbetts** [comment]
@thoemmi Awesome! Mind adding a test for this?

**Comment by anaisbetts** [comment]
It's probably easiest to do this, by cracking open one of the example fixtures `src/NSync.Tests/fixtures` and removing the dependency from the XML

**Comment by thoemmi** [comment]
I'll do

**Comment by thoemmi** [comment]
I first reverted my changes, wrote a failing unit test, reapplied my fix, and verified, that the issue is indeed fixed.

**Comment by anaisbetts** [comment]
Flawless victory. Thanks!

**Pull request merged**
