### PR TITLE
Update NuGet.Core (and some others)

### LINKED ISSUE #52: Upgrade NuGet.Core to 2.7
I don't expect any issues, but we should start using this now to ensure there's no edge case headaches.

### PR DESCRIPTION
**Pull request by shiftkey**
Resolves #52

Other things:
- muted tests which are marked as NotImplementedException
- muted `InstallManagerTests.EigenUpdateWithoutUpdateURL` which I need to resolve at some point in the future

TODO:
- get this running through a CI server (ping @xpaulbettsx)

Open questions:
- ~~should I break up these tests into "unit tests" and "integration tests" for convenience sake?~~ Not right now

### CODE REVIEW

**Comment by anaisbetts** [comment]
@shiftkey  I'll put this on my TODO list to get this running on our Janky bot

**Comment by anaisbetts** [comment]
> should I break up these tests into "unit tests" and "integration tests" for convenience sake?

Nah, no test runner in the .NET world actually makes it easy to run a subset of the tests routinely. It ends up just being busywork.

**Comment by haacked** [comment]
> Nah, no test runner in the .NET world actually makes it easy to run a subset of the tests routinely. It ends up just being busywork.

Well you can do it if you break them into separate projects.

**Comment by shiftkey** [comment]
> Well you can do it if you break them into separate projects.

I'll do that at some point in the future. Not a huge issue now.

**Pull request merged**
