### PR TITLE
Complete the Shimmer -> Squirrel transition

### PR DESCRIPTION
**Pull request by shiftkey**
TODO:
- [x] publish point releases of Squirrel.Core, Squirrel.Client and Squirrel.WixUiClient
- [x] see what @paulcbetts comes back with in terms of being able to use the `Squirrel` - fallback is Squirrel.Windows
- [x] update wiki to rename Shimmer -> Squirrel
- [ ] resolve IAppSetup test failures
- [ ] publish `0.7.6` with the right packages

### CODE REVIEW

**Comment by peters** [comment]
@shiftkey `Install-Package Squirrel.Core, Squirrel.Client -Pre` do i need anything else?

**Comment by shiftkey** [comment]
@peters i'll publish a new release of Shimmer which will use a simple NuGet trick to migrate installers across
- empty package
- depends on Squirrel [ or Squirrel.Windows]

If you're happy with uninstalling by hand, `Install-Package Squirrel.Windows` will be the way to go. I'll update the docs to reflect this - thanks for prompting me.

**Comment by peters** [comment]
Nice trick, didn't know that! :+1:

**Comment by peters** [comment]
@shiftkey what happend to you bro? :(

**Comment by shiftkey** [comment]
@peters oops, I forgot about this PR!

**Pull request closed without merging**
