### PR TITLE
0.8 - Elevate the installer only when absolutely necessary

### LINKED ISSUE #162: Installer should elevate only when it needs to installs the .NET Framework
From #142 we found that how WiX generates the installer is hard to control:
- by using a manager bootstrapper, the .NETFX needs to be installed up front
- by specifying `PerMachine="No"` the .NETFX installer doesn't elevate, which is important
- by specifying `PerMachine="Yes"` the installer always elevates, even when the .NETFX is installed, which is not ideal

Exploring some other options to be able to achieve what we need for Shimmer.

### PR DESCRIPTION
**Pull request by shiftkey**
So we have a headache which we need to investigate with how WiX and elevation works:
- as soon as a component is set as `PerMachine="False"`, the installer is elevated
- if you specify `PerMachine="True"` and do not run the installer as an elevated user, Bad Things Happen
- without the .NET Framework installed, the managed bootstrapper will not work

This PR adds a per-user DummyInstaller to the chain to prevent the elevation of the installer.

This impacted some assumptions we made about the bootstrapper process, as we should run our custom actions after the last `DetectPackageCompleteObs` item...

Tasks:
- [x] get elevation working only when the .NET Framework is not installed on the current machine
- [ ] test that the installer elevates on a machine without the .NET Framework, and finishes successfully
- [x] test that the installer does not elevate on a machine with the .NET Framework available, and finishes successfully
- [x] fix impacted tests
- [x] drop the .wixproj from the sln (it can be updated manually rather than as part of the build)
- [ ] test updated installer will correctly tidy up after updating
- [ ] investigate and resolve issues raised in testing, so the experience is really magical and stuff

Resolves #162

### CODE REVIEW

**Comment by shiftkey** [comment]
OS: Windows 7 SP1 (no framework install)

We get the elevation at the right point (no screenshot):

Prerequisites install successfully:

screen shot 2013-09-30 at 10 34 29 am

screen shot 2013-09-30 at 10 36 42 am

Our installer starts:
screen shot 2013-09-30 at 10 37 34 am

But on clicking install it navigates to the next screen but then just hangs:

screen shot 2013-09-30 at 10 38 30 am

And the logs indicate something real bad (re-running the installer at this stage also has the same behaviour)

```
[WARN][2013-09-30T10:39:38] LogHost: Couldn't load types for ReactiveUI, Version=4.6.5.0, Culture=neutral, PublicKeyToken=null: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at ReactiveUI.Reflection.<.cctor>b__22(Assembly x)
[WARN][2013-09-30T10:39:38] LogHost: Couldn't load types for Shimmer.Core, Version=0.7.2.0, Culture=neutral, PublicKeyToken=null: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at ReactiveUI.Reflection.<.cctor>b__22(Assembly x)
[WARN][2013-09-30T10:39:39] POCOObservableForProperty: Shimmer.WiXUi.Views.WelcomeView is a POCO type and won't send change notifications, WhenAny will only return a single value!
[WARN][2013-09-30T10:39:40] LogHost: Couldn't load types for ReactiveUI, Version=4.6.5.0, Culture=neutral, PublicKeyToken=null: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at ReactiveUI.Reflection.<.cctor>b__22(Assembly x)
[WARN][2013-09-30T10:39:40] LogHost: Couldn't load types for Shimmer.Core, Version=0.7.2.0, Culture=neutral, PublicKeyToken=null: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at ReactiveUI.Reflection.<.cctor>b__22(Assembly x)
[WARN][2013-09-30T10:39:40] LogHost: Couldn't load types for Shimmer.Client, Version=0.7.2.0, Culture=neutral, PublicKeyToken=null: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at ReactiveUI.Reflection.<.cctor>b__22(Assembly x)
[WARN][2013-09-30T10:39:40] POCOObservableForProperty: Shimmer.WiXUi.Views.InstallingView is a POCO type and won't send change notifications, WhenAny will only return a single value!
```

Now to do some reacting of the ReactiveUI source code...

**Comment by shiftkey** [comment]
Ignore the assembly versions here, they're not important:

```
[WARN][2013-09-30T12:36:53] LogHost: LoaderException: ReactiveUI, Version=4.6.6.0, Culture=neutral, PublicKeyToken=null: System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks, Version=2.5.19.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Threading.Tasks, Version=2.5.19.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

```
WARN][2013-09-30T12:36:53] LogHost: LoaderException: Shimmer.Core, Version=0.7.7.0, Culture=neutral, PublicKeyToken=null: System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks, Version=2.6.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Threading.Tasks, Version=2.6.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

@paulcbetts would you like a PR to update the v4 branch's Microsoft.Bcl to `1.1.3` which will make these versions the same?

After that I'll see if shipping the custom System.Threading.Tasks assembly with the installer makes this headache go away...

**Comment by shiftkey** [comment]
The other theory I have is that we need to install [the 4.0.3 update](http://www.microsoft.com/en-us/download/details.aspx?id=29053) to get some enhancements to the framework, which were necessary to get async/await backported to .NET4.

**Comment by anaisbetts** [comment]
@shiftkey Make it So

**Comment by shiftkey** [comment]
A bit more digging:

Using the framework installer that ships with WiX (it's a nicer experience):

```
<Chain>
   <PackageGroupRef Id="NetFx40Web"/>
   <!--<PackageGroupRef Id="Netfx4Full" />-->
   <MsiPackage SourceFile="$(var.ToolsDir)\DummyInstaller.msi"
                  Id="UserApplicationId"
                  Cache="yes"
                  Visible="no" />
</Chain>
```

```
*** Assembly Binder Log Entry  (9/30/2013 @ 4:03:01 PM) ***

The operation failed.
Bind result: hr = 0x80131047. No description available.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Users\brendanforster\Downloads\Setup.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: User = BRENDANFORS9FB6\brendanforster
LOG: DisplayName = System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes
 (Fully-specified)
LOG: Appbase = file:///C:/Users/brendanforster/AppData/Local/Temp/{71e529ec-24fa-4488-a66c-6a746b5ab0dc}/.ba5/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = NULL
Calling assembly : System.Threading.Tasks, Version=2.6.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\BRENDA~1\AppData\Local\Temp\{71e529ec-24fa-4488-a66c-6a746b5ab0dc}\.ba5\BootstrapperCore.config
LOG: Using host configuration file: C:\Users\BRENDA~1\AppData\Local\Temp\{71e529ec-24fa-4488-a66c-6a746b5ab0dc}\.ba5\BootstrapperCore.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: PublicKeyToken redirect found in portability config: 7cec85d7bea7798e redirected to b77a5c561934e089.
LOG: Version redirect found in portability config: 2.0.5.0 redirected to 4.0.0.0.
ERR: Failed to apply policy (hr = 0x80131047).
ERR: Unrecoverable error occurred during pre-download check (hr = 0x80131047).
```

This suggests we need an additional update to get it working as expected: http://stackoverflow.com/a/13872473

**Comment by shiftkey** [comment]
Ok, so this PR has morphed into two separate features now:
- solve the elevation headache (done) and get vanilla .NET4 installed in a VM
- install some additional patches (goddddd i suck at writing WiX syntax) to support BCL NuGet packages

Let me reopen this one and walk through solving the first issue, then I'll address the second one. :beers:

**Comment by anaisbetts** [comment]
@shiftkey  How much do we use await currently? It might be easier to just remove Microsoft.Bcl.Async and write it using (crazy) Rx syntax

**Comment by shiftkey** [comment]
> How much do we use await currently?

It's only in a couple of places.

> It might be easier to just remove Microsoft.Bcl.Async and write it using (crazy) Rx syntax

Even if we do that, the installer will then try and run the user's app (which could use async/await like my sample app does) and then it still asplodes. So I still think we need to solve it, but we can do it gradually. Baby steps.

**Pull request closed without merging**
